{% set name = "climlab-emanuel-convection" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/climlab/climlab-emanuel-convection/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d8040238a9fdd98b3d8571af4ac69458654724f5ee3309df212f6a3c983e5010

build:
  skip: true  # [py<311 or win]
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - ninja
    - pkg-config                             # [unix]
    - clang                                  # [win]
    # use flang as fortran compiler on windows (uses clang driver)
    - flang <18                              # [win]
    # use llvm linker for both of the above
    - lld                                    # [win]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}              # [unix]
  host:
    - compiler-rt                            # [win]
    - meson-python
    # limit this for now because incompatible changes
    # have accumulated in meson_dev channel for 1.4+
    - meson <1.4                             # [win]
    - python
    - python-build
    - numpy
    - pip
    - packaging >=20.0
  run:
    - python
    - numpy

test:
  requires:
    - pytest
  imports:
    - climlab_emanuel_convection
  commands:
    - pytest -v --pyargs climlab_emanuel_convection

about:
  home: https://github.com/climlab/climlab-emanuel-convection
  summary: 'Standalone Python wrapper for the Emanuel moist convection model'
  description: |
    climlab-emanuel-convection makes the Emanuel convection code callable
    from Python by wrapping using f2py. This is a lightweight wrapper that
    emulates the Fortran interface as closely as possible. The primary use case
    is to drive the convection process in climlab, but it can be used as
    a standalone driver if you are familiar with the Fortran interface.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/climlab/climlab-emanuel-convection

extra:
  recipe-maintainers:
    - brian-rose
